name: KinesteX_B2B
description: KinesteX SDK Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^9.0.0
  shared_preferences: ^2.0.13
#  flutter_inappwebview: ^6.0.0
#  provider: ^5.0.0
  kinestex_sdk_flutter: ^1.1.5

  lottie: ^2.7.0


  intl:
    ^0.17.0
  cupertino_icons: ^1.0.2


  expandable_widgets: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/yoga_animation.json
  
  uses-material-design: true